#!/bin/bash

. /etc/deepin-installer.conf

mkdir -p /target/dev
mount --bind -v --bind /dev/ /target/dev

mkdir -p /target/dev/pts
mount -vt devpts devpts /target/dev/pts

mkdir -p /target/proc
mount -vt proc proc /target/proc

mkdir -p /target/sys
mount -vt sysfs sysfs /target/sys

mkdir -p /target/media/cdrom
mount --bind /cdrom /target/media/cdrom

if [ x${DI_UEFI} == xtrue ];then
    mkdir -p /target/boot/efi
    mount ${DI_BOOTLOADER} /target/boot/efi
fi

