#!/bin/bash

echo "[$0]"
set -x

echo "-----------------------------Before Chroot Hooks ----------------------"
echo "-----------------------------DEBUG INFO: df -h ----------------------"
df -h
echo "-----------------------------DEBUG INFO: ls -lh /target/deepinhost ----------------------"
ls -lh /target/deepinhost
echo "-----------------------------DEBUG INFO: mount ----------------------"
mount
