#!/bin/bash

# Automatically create disk partitions.
# 4G for linux-swap
# Remaining space is used in three parts:
#  * 40% used as /
#  * 40% used as /var/log
#  * 20% used as backup.
# Note that all of these partitions are ext4 filesystem.

echo "[$0]"
set -x

# Print error message and exit current executation context.
error_exit() {
  echo $*
  exit 1;
}

# Umount all swap partitions.
swapoff -a

# Path to installer configuration file.
CONF_FILE='/etc/deepin-installer.conf'

# Mimumum disk capacity required, 30G.
MININUM_DISK_SIZE=30000

cp -vf "/usr/share/deepin-installer/templates/lfs-atm.conf" $CONF_FILE
# Remote group name. Group name starts with [
sed -i -e '/\[/d' $CONF_FILE

# 4G space for linux-swap.
SWAP_SIZE=4096

# The disk with largest storage capacity is used as system device.
get_max_capacity_device() {
  DEVICE=''
  MAX_CAPACITY=0
  lsblk -ndb -o NAME,SIZE 2>/dev/null | (while read NAME SIZE; do
    #echo $NAME:$SIZE
    #echo $DEVICE:$MAX_CAPACITY
    if [ $MAX_CAPACITY -lt $SIZE ]; then
      MAX_CAPACITY=$SIZE
      DEVICE=$NAME
    fi
  done && echo /dev/$DEVICE)
}

DEVICE=$(get_max_capacity_device)
if [ -z $DEVICE ]; then
  echo 'Error: no supported storage device found!';
  echo 'There shall be a IDE or SATA disk available at /dev/sda or /dev/hda';
  exit 1;
fi

DEVICE_SIZE=$(blockdev --getsize64 $DEVICE)
DEVICE_SIZE=$((DEVICE_SIZE / 1048576))
if [ $DEVICE_SIZE -lt $MININUM_DISK_SIZE ]; then
  error_exit 'Error: At least 30G is required to install!';
fi

REMAINING_SIZE=$((DEVICE_SIZE - SWAP_SIZE))

# 40% remaining space for /.
ROOT_SIZE=$((REMAINING_SIZE * 2 / 5 + SWAP_SIZE))

# 40$ for /var/log.
LOG_SIZE=$((REMAINING_SIZE * 4 / 5 + SWAP_SIZE))

# Write bootloader info to conf.
sed -i "s|DI_BOOTLOADER=.*$|DI_BOOTLOADER=\"$DEVICE\"|" $CONF_FILE
sed -i "s|DI_ROOT_DISK=.*$|DI_ROOT_DISK=\"$DEVICE\"|" $CONF_FILE

# First create a msdos partition table.
parted -s $DEVICE mktable msdos || \
  error_exit "Failed to create msdos partition on $DEVICE";

# Then create a swap partition with 4G.
parted -s $DEVICE mkpart primary linux-swap 1M ${SWAP_SIZE}M || \
  error_exit "Failed to create linux-swap on ${DEVICE}1";
mkswap ${DEVICE}1 || \
  error_exit "Failed to call mkswap ${DEVICE}1";

# And then create an ext4 partition with 20G capacity to mount /var/log
parted -s $DEVICE mkpart primary ext4 ${SWAP_SIZE}M ${ROOT_SIZE}M || \
  error_exit "Failed to create partition ${DEVICE}2";
mkfs.ext4 -F ${DEVICE}2 || \
  error_exit "Failed to make ext4 filesystem on ${DEVICE}2";
sed -i "s|DI_ROOT_PARTITION=.*$|DI_ROOT_PARTITION=\"${DEVICE}2\"|" $CONF_FILE

# Add 40% to /var/log, with ext4 type.
parted -s $DEVICE mkpart primary ext4 ${ROOT_SIZE}M ${LOG_SIZE}M || \
  error_exit "Failed to create partition ${DEVICE}3";
mkfs.ext4 -F ${DEVICE}3 || \
  error_exit "Failed to make ext4 filesystem on ${DEVICE}3";
sed -i "s|DI_MOUNTPOINTS=.*$|DI_MOUNTPOINTS=\"${DEVICE}1=swap;${DEVICE}3=/var/log;\"|" $CONF_FILE

# All remaining space is used as backup partition.
parted -s $DEVICE mkpart primary ext4 ${LOG_SIZE}M 100% || \
  error_exit "Failed to create partition ${DEVICE}4";
mkfs.ext4 -F ${DEVICE}4

# Commit to kernel.
partprobe

exit 0

