// Generated by CoffeeScript 1.10.0
(function() {
  var BoxMessage, _, bmsg, container, create_element, getQueryParams, i, j, lang, len, msg_obj, msg_obj_array,
    hasProp = {}.hasOwnProperty;

  _ = function(s, d) {
    var e, error;
    try {
      if (d) {
        return DCore.dgettext(d, s);
      } else {
        return DCore.gettext(s);
      }
    } catch (error) {
      e = error;
      return s;
    }
  };

  create_element = function(opt, parent, compatible) {
    var el, k, v;
    if (typeof compatible !== 'undefined' || typeof parent === 'string') {
      opt = {
        tag: opt,
        "class": parent
      };
      parent = compatible;
    }
    if (opt.tag == null) {
      return null;
    }
    el = document.createElement(opt.tag);
    delete opt.tag;
    for (k in opt) {
      if (!hasProp.call(opt, k)) continue;
      v = opt[k];
      el.setAttribute(k, v);
    }
    if (parent) {
      parent.appendChild(el);
    }
    return el;
  };

  getQueryParams = function(qs) {
    var params, re, tokens;
    qs = qs.split("+").join(" ");
    params = {};
    re = /[?&]?([^=]+)=([^&]*)/g;
    tokens = null;
    while ((tokens = re.exec(qs))) {
      params[decodeURIComponent(tokens[1])] = decodeURIComponent(tokens[2]);
    }
    return params;
  };

  lang = getQueryParams(document.location.search).lang;

  if (lang == null) {
    lang = "en";
  }

  document.body.lang = lang;

  console.log("[boxmessage.coffee] slideshow2014 lang:" + document.body.lang);

  BoxMessage = (function() {
    function BoxMessage(id, _class, parent1) {
      this.id = id;
      this["class"] = _class;
      this.parent = parent1;
      this.boxmessage = create_element("div", this["class"], this.parent);
      this.boxmessage.setAttribute("id", this.id);
    }

    BoxMessage.prototype.create_box_msg = function(msg_obj1) {
      var i, j, len, msg, ref, results;
      this.msg_obj = msg_obj1;
      this.title = create_element("h1", "", this.boxmessage);
      this.title.innerText = this.msg_obj.title;
      this.ul = create_element("ul", "", this.boxmessage);
      this.msg = [];
      ref = this.msg_obj.msg;
      results = [];
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        msg = ref[i];
        this.msg[i] = create_element("li", "", this.ul);
        results.push(this.msg[i].innerText = msg);
      }
      return results;
    };

    return BoxMessage;

  })();

  msg_obj_array = [
    {
      title: _("Deepin Store"),
      msg: [_("One-stop Software Management"), _("Continuous Update of Wonderful Software"), _("Unimpeded Online Communication")]
    }, {
      title: _("Deepin Movie"),
      msg: [_("Comprehensive Audio-visual Shock"), _("New Interactive Experience"), _("Intelligent Subtitle Loading")]
    }, {
      title: _("Deepin Music"),
      msg: [_("Ultimate Music Journey"), _("Rich Extended Functions"), _("Enjoy Online Strongest Voice")]
    }, {
      title: _("Deepin Community"),
      msg: [_("Free and United Open Source Community"), _("Welcome to participate in Deepin Internationalization Project"), _("Welcome to follow us on Weibo, Twitter, Facebook, Google+, Mailing List and IRC")]
    }
  ];

  container = document.getElementById('container');

  bmsg = [];

  for (i = j = 0, len = msg_obj_array.length; j < len; i = ++j) {
    msg_obj = msg_obj_array[i];
    bmsg[i] = new BoxMessage("text" + (i + 1), "text" + (i + 1) + " messages", container);
    bmsg[i].create_box_msg(msg_obj);
  }

  document.body.addEventListener("contextmenu", (function(_this) {
    return function(e) {
      e.preventDefault();
      return e.stopPropagation();
    };
  })(this));

}).call(this);
