#!/bin/sh

PREREQ=""
DESCRIPTION="Configure Auto Deepin Installer..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"


generate_lightdm_conf()
{
(
cat <<EOF
[SeatDefaults]
greeter-session=deepin-lightdm-language-selector
user-session=deepin-livecd-installer
EOF
) > $1
}

for x in $(cat /proc/cmdline); do
    case $x in
	livecd-installer)
        live_mode=true
        ;;
    esac
done

if [ "$live_mode" = "true" ]; then
	chroot /root mount -o remount,rw /
	$(generate_lightdm_conf /root/etc/lightdm/lightdm.conf)
	chroot /root mount -o remount,ro /
fi

log_end_msg

