#!/usr/bin/python

import glob
import os
import re

coffee_files = []
html_files = []
c_files = []
except_dirs = ["dbus_test", "memory_test", "dominant_color"]

def get_lang():
    pos = glob.glob("./*.po")
    for po in pos:
        rec = re.compile("./([a-zA-Z_]+)\.po")
        result = rec.match(po)
        yield result.group(1)


def get_files():
    global coffee_files,html_files, c_files
    for d in os.listdir("../resources"):
        if d != "common" and d not in except_dirs:
            coffee_files += glob.glob("../resources/%s/js/*.coffee" % d)
            html_files += glob.glob("../resources/%s/ppt/*/*.coffee" % d)
    for d in os.listdir("../app"):
        if d not in except_dirs:
            c_files += glob.glob("../app/%s/*.c" % d);
            c_files += glob.glob("../app/%s/*.h" % d);

    c_files += [
            ]


def scan():
    global coffee_files, html_files, c_files
    os.system("rm installer.pot")
    for l in get_lang():
        os.system("touch installer.pot")
        os.system("touch %s.po" % l)

        cmd= "xgettext --from-code=utf-8 -L python -j -o installer.pot " + " ".join(coffee_files)
        os.system(cmd)

        cmd= "xgettext --from-code=utf-8 -L python -j -o installer.pot " + " ".join(html_files)
        os.system(cmd)

        cmd = "xgettext --from-code=utf-8 -k_ -j -o installer.pot " + " ".join(c_files)
        os.system(cmd)

        os.system("msgmerge %s.po installer.pot > new_%s.po" % (l, l))

        os.system("mv new_%s.po %s.po" % (l, l))

if __name__ == '__main__':
    get_files()
    scan()
