#!/usr/bin/python

import glob
import os
import re

coffee_files = []
c_files = []
except_dirs = ["dbus_test", "memory_test", "dominant_color"]
app = "deepin-installer"

def get_lang():
    pos = glob.glob("./*.po")
    for po in pos:
        rec = re.compile("./([a-zA-Z_]+)\.po")
        result = rec.match(po)
        yield result.group(1)


def get_files():
    global coffee_files, c_files

    for d in os.listdir("../resources"):
        if d != "common" and d not in except_dirs:
            coffee_dir = "../resources/%s/js/" % d
            for dirpath, dirnames, filenames in os.walk(coffee_dir):
                for filename in filenames:
                    if filename.endswith(".coffee"):
                        coffee_files.append(os.path.join(dirpath, filename))
    #TODO:Here add your app coffee files in special dir
    coffee_files.append(os.path.join("../resources/installer/ppt/*/*.coffee"))

    for d in os.listdir("../app"):
        if d not in except_dirs:
            c_files += glob.glob("../app/%s/*.c" % d);
            c_files += glob.glob("../app/%s/*.h" % d);

    #TODO:Here add your app c files in special dir
    c_files += [
            ]

def scan_pot():
    global coffee_files, c_files
    os.system("rm %s.pot" % app)
    os.system("touch %s.pot" % app)

    cmd= "xgettext --from-code=utf-8 -L python -j -o %s.pot " % app + " ".join(coffee_files)
    os.system(cmd)

    cmd = "xgettext --from-code=utf-8 -k_ -j -o %s.pot " % app + " ".join(c_files)
    os.system(cmd)

if __name__ == '__main__':
    get_files()
    scan_pot()
