#!/bin/bash
# install grub to detect machine

if [ ! -d /sys/firmware/efi ];then
    BOOT="legacy"
else
    BOOT="efi"
fi

# add cdrom to source.list
 [ ! -d /media/cdrom ] && exit 0
apt-cdrom add -d /media/cdrom -m  && apt-get update

GRUB_TARGET="/dev/sda"

if [ -f /etc/deepin-installer.conf ];then
    . /etc/deepin-installer.conf
fi

#TODO detect secureboot

case ${BOOT} in
    "efi")
        echo "INFO: Detected efi machine"
        apt-get install --no-install-recommends -y --force-yes --allow-unauthenticated grub-efi
        grub-install --target=x86_64-efi --efi-directroy=/boot/efi --bootloader-id=linuxdeepin2014 --recheck --debug
        ;;
    "legacy")
        echo "INFO: Detected legacy machine"
        # if still not work, uncomment blow code.
        ## echo "set grub-pc/install_devices ${GRUB_TARGET}" | debconf-communicate
        DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --force-yes --no-install-recommends --allow-unauthenticated install grub-pc
        
        grub-install --no-floppy --force ${GRUB_TARGET}
        ;;
    "uefi-secureboot")
        apt-get install --no-install-recommends -y --force-yes --allow-unauthenticated sbsigntool grub-efi-amd64-signed linux-signed-generic
        grub-install --uefi-secure-boot --efi-directroy=/boot/efi
        ;;
esac

update-grub
