#! /bin/sh
# Disable 'auto dhcp' interfaces if network-manager is in use.
# when use PXE install system will cause this problem.

if [ -f /etc/NetworkManager/NetworkManager.conf ]; then
  sed  -i 's/managed=false/managed=true/' /etc/NetworkManager/NetworkManager.conf
fi

if [ ! -e /etc/resolv.conf ]; then
    ln -nsf ../run/resolvconf/resolv.conf /etc/resolv.conf
fi
