#! /bin/sh
# Disable 'auto dhcp' interfaces if network-manager is in use.
# when use PXE install system will cause this problem.
set -e

if [ -f /etc/NetworkManager/NetworkManager.conf ]; then
  sed  -i 's/managed=false/managed=true/' /etc/NetworkManager/NetworkManager.conf
fi
exit 0
