#!/bin/bash
HOOKSPATH=/usr/share/installer/resources/hooks

. ${HOOKSPATH}/00job_install_grub
. ${HOOKSPATH}/55-netcfg-network-manager
. ${HOOKSPATH}/56enable-network-manager
. ${HOOKSPATH}/57select-grub-packages
. ${HOOKSPATH}/90remove-unused-packages

exit 0
